# Generated by Django 5.1.3 on 2024-11-30 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='desactivado',
            new_name='vigencia',
        ),
    ]
